typography_spectrum: 0.25736
color:
  brandColors:
    - '#16bcc6'
    - '#0bb9c2'
    - '#00b4bd'
    - '#10bbc4'
    - '#04b7c0'
  brandStrength: 0.6875
  lightness: 0.6438969
  saturation: 0.375
  rhythmicContrast: 0.3069653
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.74046
analytics:
  google: null
  facebook: null
  twitter: null
name: Semioticlabs
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: About us
    id: 07dda057-9aaf-4b1c-9476-16429486e5be
    type: content
favicon: null
purpose: []
